# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts

# Copy server files
COPY server ./server
COPY manifest.json .

# Default environment
ENV NODE_ENV=production

# Expose nothing, stdio
CMD ["node", "server/index.js"]
